# Пример настройки docker-compose для микросервисной архитектуры

version: '3.8'

services:
  # Auth сервис
  auth:
    build: ./auth
    container_name: levelupper_auth
    ports:
      - "8001:8000"
    environment:
      - DB_HOST=postgres
      - DB_NAME=auth_db
      - DB_USER=auth_user
      - DB_PASSWORD=auth_pass
      - REDIS_HOST=redis
    networks:
      - levelupper_network
    depends_on:
      - postgres
      - redis

  # Основной сервис (back)
  main:
    build: ./back
    container_name: levelupper_main
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=postgres
      - DB_NAME=main_db
      - DB_USER=main_user
      - DB_PASSWORD=main_pass
      - REDIS_HOST=redis
      - AUTH_SERVICE_URL=http://auth:8000  # Внутренняя связь между контейнерами
      - AUTH_SERVICE_TIMEOUT=30.0
    networks:
      - levelupper_network
    depends_on:
      - postgres
      - redis
      - auth  # Зависимость от auth-сервиса

  # Frontend
  frontend:
    build: ./front
    container_name: levelupper_frontend
    ports:
      - "3000:80"
    environment:
      - AUTH_API_URL=http://localhost:8001  # Публичный URL для браузера
      - MAIN_API_URL=http://localhost:8000  # Публичный URL для браузера
    networks:
      - levelupper_network
    depends_on:
      - auth
      - main

  # PostgreSQL
  postgres:
    image: postgres:15
    container_name: levelupper_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_pass
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init-multi-db.sh:/docker-entrypoint-initdb.d/init-multi-db.sh:ro
    networks:
      - levelupper_network

  # Redis
  redis:
    image: redis:7-alpine
    container_name: levelupper_redis
    ports:
      - "6380:6379"
    networks:
      - levelupper_network

networks:
  levelupper_network:
    driver: bridge

volumes:
  postgres_data:

# Переменные окружения для разработки
# Создайте файл .env в корне проекта:
#
# # Auth service
# AUTH_SERVICE_URL=http://localhost:8001
# AUTH_SERVICE_TIMEOUT=30.0
#
# # Database for main service
# DB_HOST=localhost
# DB_PORT=5433
# DB_NAME=main_db
# DB_USER=main_user
# DB_PASSWORD=main_pass
#
# # Redis
# REDIS_HOST=localhost
# REDIS_PORT=6380