"""change_patient_name

Revision ID: 752f6b54f20d
Revises: f66721b00a1d
Create Date: 2025-03-19 17:40:31.423889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '752f6b54f20d'
down_revision: Union[str, None] = 'f66721b00a1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('patient_name_key', 'patient', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('patient_name_key', 'patient', ['name'])
    # ### end Alembic commands ###
